### ISSUE TITLE
[bug] Cryptic error message when calling speep get -all

### ISSUE THREAD

**Issue by kinbiko** [snkzt/shortcut-peeper#11]
## What I did

I ran
```
$ speep get -all
```
immediately after installing the app.

## What I got

```
please add new shortcuts, no shortcut key registered: failed to retrieve shortcut list: failed to retrieve env path: failed to create directory "speep": mkdir /Users/kinbiko/.config/.config/speep: no such file or directory
```

## What I expected

I think there may be too many `.config/.config` directories expected...

Also it would be good to have a user-friendly helpful message.
As a user (pretending like I don't know the implementation details of the app) I don't know how to fix this.

**Comment by snkzt** [comment]
TODO: address to the point below
>Also it would be good to have a user-friendly helpful message.
As a user (pretending like I don't know the implementation details of the app) I don't know how to fix this.

**Comment by snkzt** [comment]
Now the message only appears when there is no shortcut key is registered.
I will improve the message itself in #29 
```
$ shortcut-peeper (reduce-pointer-usage) speep get -a
please add new shortcuts, no shortcut key registered: failed to open shortcut list: open /Users/snkzt/.config/speep/shortcuts.json: no such file or directory
$ shortcut-peeper (reduce-pointer-usage) speep add -c shell -n copy -k ctrl+c
New shortcut "copy" for shell successfully registered%                                   
$ shortcut-peeper (reduce-pointer-usage) speep get -a
Category  Name  Shortcut key

shell    copy    ctrl+c 
```
