### ISSUE TITLE
[bug] Calling speep with unsupported arguments fails silently

### ISSUE THREAD

**Issue by kinbiko** [snkzt/shortcut-peeper#9]
## What I did

```
$ speep asdlkfjhasdlkfjhasdf
```

## What I got

Nothing.
No output. Return code 0 (indicating it was OK).

## What I expected

Non-zero return code and some warning message like:

```
speep: supported sub-commands: add, delete, get
```

**Comment by snkzt** [comment]
Added the message below for the release v0.2.0, but will update this to navigate users to --help which suggested in issue #10 
>Please check how to use the app by typing either "speep get", "speep add" or "speep delete" for more details.

**Comment by snkzt** [comment]
Updated the error message to show usage in v0.3.0
